### ISSUE TITLE
Use attribute 'label' if no attribute 'labels' to print labels when `View` is used in Rstudio

### ISSUE THREAD

**Issue by ghost** [ekstroem/dataMaid#21]
# Description

The usage of the attribute *label* lead to show the value of this attribute under the name of the column when the data.frame is viewed interactively in Rstudio with the `View` function.

e.g., (to run in Rstudio):

```r
data(cars)
View(cars) # No label 
attr(cars$speed, 'label') <- "Speed of the car"
View(cars) # Print gently the label under the column names
```

# Problem

In dataMaid, it's possible to use a label. However, it's named 'labels' (with an extra *s*) and then not used in Rstudio table viewer.

# Possible solution

In `unpackLabelled.R`

```r
unpackLabelled <- function(v) {
  labels <-  attributes(v)$labels
  if (!is.null(labels)) {
     return(c(as.character(v), attributes(v)$labels))
  } else {
    return(c(as.character(v), attributes(v)$label))
  }
}
```

**Comment by ekstroem** [comment]
Thanks for reporting this.

And d'oh! That is a mistake on my part. It should be the `label` attribute and not `labels` which is concerned with coding values like a factor variable. I'll push an update here later today and leave `labels` in for a few generations. That being said ... I do think `label` already works since we're not actually using exact matching for the `attr` call internally.
