### ISSUE TITLE
Error in hist.Date(v, plot = FALSE) :    Must specify 'breaks' in hist(<Date>)

### ISSUE THREAD

**Issue by jclchan** [ekstroem/dataMaid#44]
I generate summary outputs on a dataframe with some Date variables, 

makeDataReport(df_active_site, output='html', replace=TRUE, file=paste0(proj_dir, '../dataMaid outputs/active_site.Rmd'))

and it showed up errors below with the outputted HTML missing almost all outputs after that Date variable:

Error in hist.Date(v, plot = FALSE) : 
  Must specify 'breaks' in hist(<Date>)
Data report generation is finished. Please wait while your output file is being rendered.

Can you help to fix it?

**Comment by annennenne** [comment]
This is a bug in the CRAN version of the package. We have fixed it some time ago in the Github version of the package. 

There are two work arounds. You can either use "basicVisual" (base R) plots rather than "standardVisual" (ggplot2) plots:
```  
library(dataMaid)
data(testData)
makeDataReport(testData, visuals = setVisuals(all = "basicVisual))
``` 

or you can install and use the development version of `dataMaid` from Github;
```
library(devtools)
install_github("ekstroem/dataMaid")
library(dataMaid)
data(testData)
makeDataReport(testData)
``` 
which should work.

**Comment by jclchan** [comment]
Thanks for your reply. It works!
