### ISSUE TITLE
makeCodeBook pdf problems

### ISSUE THREAD

**Issue by WeeBeasties** [ekstroem/dataMaid#45]
I cannot knit codebooks or reports to pdf any longer (I once could, but I've updated RStudio and R). I can knit to pdf with other projects, so I know that my Tex installation is working. The error I get is this:

! LaTeX Error: \begin{minipage} on input line 1321 ended by \end{document}.

**Comment by annennenne** [comment]
Can you provide a minimal example that produces the error? I cannot find a way to trigger it myself. 

And while we try to find a solution, I think that you should be able to render to pdf if you choose `twoCol = FALSE` in your `makeDataReport()` call:
```
makeDataReport(data, twoCol = FALSE)
``` 
This will change the layout so that the summary table and the distribution visualization are no longer side by side, but I believe it should be able to run.

**Comment by ekstroem** [comment]
I have a vague notion that this might be fixed in the current development version. 
Did you install the package from CRAN (say after upgrading to R 3.6.0) or directly from GitHub?

**Comment by WeeBeasties** [comment]
I believe that I installed from CRAN after upgrading. Setting `twoCol = FALSE` does indeed solve the problem for me and I am fine with that as a workaround. Here is a minimal example that kicks up the error for me. Rendering to HTML or Word has no problems...

`library(dataMaid)

myData <- data.frame(One = rnorm(n = 20, mean = 10, sd = 2), Two = rnorm(n = 20, mean = 30, sd = 5), Three = rep("Test", 20))

makeCodebook(myData, replace = TRUE)`

**Comment by WeeBeasties** [comment]
Out of curiosity, I reloaded the package using the GitHub repo this time. After restarting RStudio, the codebook generates properly. My problem is solved.

**Comment by ekstroem** [comment]
Thanks for checking this. Guess it's time to push a new version to CRAN to capture all the R 3.6.0 update problems.
