### ISSUE TITLE
Extending dataMaid Vignette is ill-formatted

### ISSUE THREAD

**Issue by jakob-r** [ekstroem/dataMaid#50]
At least it renders wrong on CRAN

https://cran.r-project.org/web/packages/dataMaid/vignettes/extending_dataMaid.html

**Comment by annennenne** [comment]
Thanks for letting us know! I believe I have fixed it in the development version here on Github, and so it will also be fixed in the CRAN version next time we do an update. 

Meanwhile, a correctly formatted vignette can be obtained by installing the github version of the package with `build_vignettes = TRUE`:
```
    devtools::install_github("ekstrom/dataMaid", build_vignettes = TRUE)
    library(dataMaid)
    vignette("extending_dataMaid")
```
