### ISSUE TITLE
Provide metadata in the reports

### ISSUE THREAD

**Issue by richierocks** [ekstroem/dataMaid#6]
It would be useful if the reports contained some metadata, including

- The name of the person who created the report. (See `whoami::fullname()`.)
- The time and date that the report was created.
- The version of R being used.
- The version of `dataMaid` being used.
- Any options that were set in the call to `clean()`.

**Comment by annennenne** [comment]
Thanks for the input! 

Can you expand on what type of metadata you are refering to? Specifically, I'm wondering if you are interested in "proper" meta data in e.g. the pdf-file (that is, meta data that is not readily readable for the user) or rather printed information in the reports (along the lines of the `dataMaid` version number that is always printed at the end of a report)?

**Comment by richierocks** [comment]
I'd prefer something that is readable by the user, on the first page (so it is easy to spot if you have done something silly like use an outdated version of something, or if the report is an old copy.)

In addition to the list of possible values mentioned at the start of this thread, reporting on the operating system used may also be helpful.

**Comment by ekstroem** [comment]
A few notes to consider re this. I've added some of the information to the end of the output - we can add stuff, combine it in a table later, and put it somewhere else. The "biggest" problem is for pdf output since the output currently uses the LaTeX `report` documentclass, and we need to tweak the title page. Possibly solutions would be to 

1.  use the `titlepages` LaTeX package (although that puts an extra requirement on the end user which would be nice to avoid)?
2.  swap to `article` documentclass and tweak the LaTeX output.

**Comment by ekstroem** [comment]
Fixed. Formatting etc may be changed later
